server:
  port: 18180
  servlet:
    context-path: /achievements
spring:
  datasource:
    url: jdbc:mysql://47.96.2.117:3306/staff_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j2 #lcx
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
stu:
  A: 10
  B: 10
  K1: 1
  K2: 2
  K3: 1.5
passage:
  DTOP: 2400
  TOP: 270
  A: 120
  B: 50
  C: 20
  D: 10
patent:
  A: 30
  B: 10