server:
  port: 18180
  servlet:
    context-path: /achievements
spring:
  datasource:
    url: jdbc:mysql://47.96.2.117:3306/staff_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j2 #lcx
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true